In [1]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5]) 
print(arr) 


[1 2 3 4 5]


In [2]:

D= np.arange(1000) 

print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize) 


Size of the whole Numpy array in bytes:  8000


In [3]:
arr = np.array(42) 
print(arr) 


42


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr) 


[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) 
print(arr) 


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
zeros_arr = np.zeros((5,2)) 
eros_arr = np.zeros(5) 
print(zeros_arr) 

zeros_arr = np.zeros((2,3)) 
print(zeros_arr) 




[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:

ones_arr = np.ones(6) 
print(ones_arr) 


[1. 1. 1. 1. 1. 1.]


In [12]:
arr1 = np.arange(10) 
arr2 = np.random. randn (10) 
print("array 1\n", arr1, arr1.dtype) 
print("Array 2 \n", arr2, arr2.dtype) 
new_arr = arr1.astype (arr2.dtype) 
arr1.astype(arr2.dtype) 
print("New Array \n", new_arr, new_arr.dtype) 


array 1
 [0 1 2 3 4 5 6 7 8 9] int64
Array 2 
 [-0.96426484 -0.90007433  2.10121711 -0.91618089 -2.00140033 -1.30763102
  0.73356965  1.87811969  0.80871203 -0.50843778] float64
New Array 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [13]:
str_arr = np.array(['hello', 'world', 'numpy']) 
print(str_arr) 


['hello' 'world' 'numpy']


In [19]:

x = np.arange(10) 
print(x) 
x[5] = 2 
print("\n After broadcasting1",x) 
x[::2] = 100 
print("\n After broadcasting2",x) 


[0 1 2 3 4 5 6 7 8 9]

 After broadcasting1 [0 1 2 3 4 2 6 7 8 9]

 After broadcasting2 [100   1 100   3 100   2 100   7 100   9]


In [22]:

a = np.arange(12). reshape (3,4) 
print("a= \n",a) 
b = a > 4 
print("b= \n", b) 
print("a[b]= \n",a[b]) 
a [b] = 1 
print("a= \n",a) 



a= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b= 
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
a[b]= 
 [ 5  6  7  8  9 10 11]
a= 
 [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [25]:

import numpy as np 
arr = np.arange(12).reshape((3, 4)) 
print(arr) 
print("Transpose using .T") 
print(arr.T) 
print("Transpose using the transpose() function") 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose using .T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Transpose using the transpose() function


In [26]:
arr1=np.transpose(arr, (1, 0)) 
print(arr1) 
arr2=np.transpose(arr, (0,1)) 
print(arr2) 


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:

print(arr) 
print("Swap axes 0 and 1:") 
print(np.swapaxes (arr, 0, 1)) 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swap axes 0 and 1:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [35]:
arr = np.arange(12).reshape((3, 4)) 
print(arr) 
print("Swap axes 0 and 1:") 
print(np.swapaxes (arr, 0, 1)) 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swap axes 0 and 1:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
